name: Lint & Type Check

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (check)
        run: black --check .

      - name: Mypy (type check)
        # mypy will read configuration and the target "files" from pyproject.toml
        run: mypy